# Generated by Django 5.0.3 on 2024-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0002_remove_order_customer_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images/', width_field='width'),
        ),
    ]
